# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_macOS:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Print
      run: echo $(ls)
      
    - name: Build
      run: xcodebuild build -project KVOMagic/KVOMagic.xcodeproj -scheme KVOMagic -derivedDataPath ci_build -configuration Release
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: KVOMagic_Mac
        path: ci_build/Build/Products/Release
  build_iOS:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: xcodebuild build -project KVOMagic/KVOMagic.xcodeproj -scheme KVOMagic -derivedDataPath ci_build -configuration Release -destination generic/platform=iOS
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: KVOMagic_iOS
        path: ci_build/Build/Products/Release-iphoneos
  build_tvOS:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: xcodebuild build -project KVOMagic/KVOMagic.xcodeproj -scheme KVOMagic -derivedDataPath ci_build -configuration Release -destination generic/platform=tvOS
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: KVOMagic_tvOS
        path: ci_build/Build/Products/Release-appletvos
